<section page="info">
    <div class="list">
        <h2>Co je to Webhosting?</h2>
        <p>Webhosting je pronájem prostoru pro vaše webové stránky. Zjednodušeně řečeno je to místo rezervované pro váš web na cizím počítači, který je neustále připojen k internetu.</p>
        <h2>Co je to Doména?</h2>
        <p>Doména slouží k snadnému zapamatování a jednoznačné identifikaci webových stránek. Zapamatovat si IP adresy jednotlivých webových stránek by bylo náročné proto se nahrazují doménou. Doména je např. sps-karvina.cz.<br>K zobrazení webové stránky je avšak potřeba znát IP adresu. K její zjištění nám slouží DNS server.</p>
        <h2>Co je to DNS?</h2>
        <p>Tento systém převádí domény na IP adresy. Prohlížeš se před odesláním požadavku obrátí na tento systém, aby zjistil IP adresu serveru, na který má požadavek směřovat.</p>
        <h2>Co je to HTML?</h2>
        <p>HTML je <strong>značkovací</strong> jayzk, ve kterém definujeme obsah webových stránek. Tedy vše to co má být zobrazeno.</p>
        <h2>Co je to CSS?</h2>
        <p>CSS jsou <strong>kaskádové styly</strong>, které definují jak má vytvořený obsah v HTML vypadat.</p>
        <h2>Co je to JavaScript(JS)?</h2>
        <p>JavaScript je <strong>skriptovací</strong> jazyk, který běží na straně klienta. Nejačastěji se používá pro tvorbu interaktivních stránek, vyskakovacích oken či efektů.</p>
        <h2>Co je to PHP?</h2>
        <p>PHP je <strong>skriptovací</strong> jazyk, který narozdíl od JavaScriptu běži na straně serveru. Slouží především k generování obsahu na základě dat v databázi.</p>
        <h2>Co je to SQL?</h2>
        <p>SQL je <strong>sktrukturovaný</strong> jazyk, který se používá pro komunikaci s databází.</p>
        <h2>Co je to JSON?</h2>
        <p>JSON je způsob zapísu dat, který slouží především pro přenos dat. Nejčastěji se s ním setkáte u API.</p>
        <h2>Co je to API?</h2>
        <p>Je to způsob komunikace mezi dvěma zařízeními, které si vzájemně vyměňují data. Ve světe webových stránek to je klient(prohlížeč), který posílá HTTP požadavky na server a ten odpovídá daty nejčastěji zakódovanými v JSON.</p>
        <h2>Co je to HTTP?</h2>
        <p>HTTP je protokol používáný k zobrazení webové stránky. Když uživatel zadá URL adresu, prohlížeč odešle serveru HTTP požadavek a získá odpověď ve formě HTML kódu, který následně zobrazí.</p>
        <h2>Co je to HTTPS?</h2>
        <p>HTTPS se zabezepčená verze protokolu HTTP. Pro navázání zabezpečené komunikace je zapotřebí SSL případně TLS certifikát.</p>
        <h2>Co je to FTP?</h2>
        <p>FTP je protokol, který slouží k přenosu souborů mezi počítači. Tento protokol umožňuje uživatelům nahrávat soubory na server nebo je stahovat z něj. FTP poskytuje způsob, jak spravovat a aktualizovat obsah webových stránek, přičemž uživatelé mohou přistupovat ke svým souborům na vzdáleném serveru pomocí FTP klientů.</p>
        <h2>Co je to objektově orientované programování(OOP)?</h2>
        <p>OOP je způsob programování za pomocí tříd a objektů. Pro tvrobu rozsáhlých aplikací je nutnost tento způsob programování ovládat.</p>
    </div>
</section>