<section page="weby">
    <div class="page-block-list">
        <?php foreach ($this->data->get('websites') as $web) : ?>
            <div class="block">
                <div class="block-title">
                    <span class="block-title"><?= $web['website_name'] ?></span>
                </div>
                <div class="block-body">
                    <a href="/Websites/<?= $web['login'] ?>/<?= $web['website_name'] ?>/">Zobrazit</a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</section>