<!DOCTYPE html>
<html lang="cs">
    <?php require ROOT . '/Styles/Templates/Blocks/Head.phtml'; ?>
    <body>
        <div class="page page-stretch">
            <div class="page-header">
                <h1>Vyskytla se chyba!</h1>
                <a href="/">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--!Font Awesome Free 6.7.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l192 192c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L77.3 256 246.6 86.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-192 192z"/></svg>
                    <span>Zpět do panelu</span>
                </a>
            </div>
            <div class="page-body">
                <div class="block">
                    <div class="block-title">
                        <span class="block-title"><?= $this->data->get('error') ?></span>
                    </div>     
                </div>
            </div>
        </div>
        <?php require ROOT . '/Styles/Templates/Blocks/Bottom.phtml'; ?>
    </body>
</html>